/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fpt.uebung8;

public class App {
    public static void main(String[] args) {
       System.out.println("hi");
    }
}
